name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'true'
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4

      - 
        name: Generate version based on date
        id: version
        run: echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/abox:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/abox:${{ env.VERSION }}
